name: CI Tests

on:
  pull_request:
    branches: [main]
    types: [opened] # Only on PR creation, not on synchronize (new commits)
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  test:
    name: Run Unit Tests Only
    runs-on: ubuntu-latest

    outputs:
      test-result: ${{ steps.test-step.outputs.result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests only
        id: test-step
        run: |
          echo "🧪 Running unit tests only..."
          # Run only unit tests with clean output (no colors/ANSI codes)
          npx vitest run src/App.test.jsx src/utils/counterUtils.test.js --reporter=verbose --no-color 2>&1 | tee test-output.log
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "result=success" >> $GITHUB_OUTPUT
            echo "✅ Unit tests passed!" >> test-summary.md
          else
            echo "result=failure" >> $GITHUB_OUTPUT
            echo "❌ Unit tests failed!" >> test-summary.md
          fi
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-output.log
            test-summary.md

      - name: Comment test results on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            let testOutput = '';
            let testSummary = '';

            try {
              testOutput = fs.readFileSync('test-output.log', 'utf8');
              // Clean up any remaining ANSI codes and excessive whitespace
              testOutput = testOutput
                .replace(/\x1b\[[0-9;]*m/g, '') // Remove ANSI escape codes
                .replace(/\s+$/gm, '') // Remove trailing whitespace
                .split('\n')
                .filter(line => line.trim() !== '') // Remove empty lines
                .slice(-15) // Take last 15 meaningful lines
                .join('\n');
            } catch (e) {
              testOutput = 'No test output available';
            }

            try {
              testSummary = fs.readFileSync('test-summary.md', 'utf8');
            } catch (e) {
              testSummary = 'No test summary available';
            }

            const testResult = '${{ steps.test-step.outputs.result }}';
            const emoji = testResult === 'success' ? '✅' : '❌';
            const status = testResult === 'success' ? 'PASSED' : 'FAILED';

            const comment = `
            ## ${emoji} Unit Tests: ${status}

            ${testSummary}

            ### Clean Test Output
            \`\`\`
            ${testOutput}
            \`\`\`

            ${testResult === 'failure' ? 
              '⚠️ **This PR cannot be merged until all unit tests pass.**' : 
              '🎉 **Unit tests passed! This PR is ready for review.**\n\n💡 **To merge this PR:** Comment `:runMerge` to trigger all tests and merge.'
            }

            ---
            *Automated unit test run for commit ${context.sha.substring(0, 7)}*
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  deploy-check:
    name: Deployment Check
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && needs.test.outputs.test-result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build

      - name: Test production build
        run: |
          npm run preview &
          PID=$!
          sleep 5
          curl -f http://localhost:4173 || exit 1
          kill $PID

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
